/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import jssc.SerialPortException;
import stream.StreamData;

/**
 *
 * @author xyges
 */
public class Control extends javax.swing.JInternalFrame {

    PanamaHitek_Arduino teensy;
    int inhibidorTemp = 0;
    int inhibidorHume = 0;
    StreamData datos;

    public Control(PanamaHitek_Arduino teensy, StreamData datos) {
        this.teensy = teensy;
        this.datos = datos;
        initComponents();
        jSliderTemperatura.setMaximum(33);
        jSliderTemperatura.setMinimum(25);
        jSliderTemperatura.setValue(datos.estadoActualTemp);
        jSliderHumedad.setMaximum(80);
        jSliderHumedad.setMinimum(50);
        jSliderHumedad.setValue(datos.estadoActualHume);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPMAhorroEnergia = new javax.swing.JTabbedPane();
        jPanelMAhorroEnergia = new javax.swing.JPanel();
        jToggleButtonEnergia = new javax.swing.JToggleButton();
        jPanelConfort = new javax.swing.JPanel();
        jToggleButtonConfort = new javax.swing.JToggleButton();
        jSliderTemperatura = new javax.swing.JSlider();
        jSliderHumedad = new javax.swing.JSlider();
        jLabelTemperatura = new javax.swing.JLabel();
        jLabelHumedad = new javax.swing.JLabel();
        jLabelTempL = new javax.swing.JLabel();
        jLabelHumeL = new javax.swing.JLabel();
        jPAccidentes = new javax.swing.JPanel();
        jToggleButtonAccidentes = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButtonIntrusos = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Panel de control");

        jToggleButtonEnergia.setText("Manual");
        jToggleButtonEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEnergiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMAhorroEnergiaLayout = new javax.swing.GroupLayout(jPanelMAhorroEnergia);
        jPanelMAhorroEnergia.setLayout(jPanelMAhorroEnergiaLayout);
        jPanelMAhorroEnergiaLayout.setHorizontalGroup(
            jPanelMAhorroEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMAhorroEnergiaLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jToggleButtonEnergia)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanelMAhorroEnergiaLayout.setVerticalGroup(
            jPanelMAhorroEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMAhorroEnergiaLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jToggleButtonEnergia)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTPMAhorroEnergia.addTab("Energía", jPanelMAhorroEnergia);

        jToggleButtonConfort.setText("Manual");
        jToggleButtonConfort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonConfortActionPerformed(evt);
            }
        });

        jSliderTemperatura.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderTemperatura.setPaintLabels(true);
        jSliderTemperatura.setPaintTicks(true);
        jSliderTemperatura.setSnapToTicks(true);
        jSliderTemperatura.setName(""); // NOI18N
        jSliderTemperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderTemperaturaStateChanged(evt);
            }
        });

        jSliderHumedad.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderHumedad.setPaintLabels(true);
        jSliderHumedad.setPaintTicks(true);
        jSliderHumedad.setSnapToTicks(true);
        jSliderHumedad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHumedadStateChanged(evt);
            }
        });

        jLabelTemperatura.setText("Temperatura");

        jLabelHumedad.setText("Humedad");

        jLabelTempL.setText("27 ºC");

        jLabelHumeL.setText("60 %");

        javax.swing.GroupLayout jPanelConfortLayout = new javax.swing.GroupLayout(jPanelConfort);
        jPanelConfort.setLayout(jPanelConfortLayout);
        jPanelConfortLayout.setHorizontalGroup(
            jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfortLayout.createSequentialGroup()
                .addGroup(jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfortLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTemperatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelConfortLayout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(jToggleButtonConfort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addGroup(jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTempL)
                    .addComponent(jSliderTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfortLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabelHumedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderHumedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfortLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHumeL)
                        .addGap(40, 40, 40))))
        );
        jPanelConfortLayout.setVerticalGroup(
            jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfortLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderHumedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConfortLayout.createSequentialGroup()
                        .addComponent(jSliderTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConfortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHumeL)
                            .addComponent(jLabelTempL, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabelHumedad)
                    .addGroup(jPanelConfortLayout.createSequentialGroup()
                        .addComponent(jLabelTemperatura)
                        .addGap(72, 72, 72)
                        .addComponent(jToggleButtonConfort)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTPMAhorroEnergia.addTab("Confort", jPanelConfort);

        jToggleButtonAccidentes.setText("Manual");
        jToggleButtonAccidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAccidentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAccidentesLayout = new javax.swing.GroupLayout(jPAccidentes);
        jPAccidentes.setLayout(jPAccidentesLayout);
        jPAccidentesLayout.setHorizontalGroup(
            jPAccidentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAccidentesLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jToggleButtonAccidentes)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPAccidentesLayout.setVerticalGroup(
            jPAccidentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAccidentesLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jToggleButtonAccidentes)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTPMAhorroEnergia.addTab("Accidentes", jPAccidentes);

        jToggleButtonIntrusos.setText("Manual");
        jToggleButtonIntrusos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonIntrusosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jToggleButtonIntrusos)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jToggleButtonIntrusos)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTPMAhorroEnergia.addTab("Intrusos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPMAhorroEnergia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPMAhorroEnergia)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonAccidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAccidentesActionPerformed
        if (jToggleButtonAccidentes.getText().equals("Manual")) {
            jToggleButtonAccidentes.setText("Automatico");
            try {
                teensy.sendData("zzzzzzzzzz");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            jToggleButtonAccidentes.setText("Manual");
            try {
                teensy.sendData("yyyyyyyyyy");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_jToggleButtonAccidentesActionPerformed

    private void jToggleButtonConfortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonConfortActionPerformed
        if (jToggleButtonConfort.getText().equals("Manual")) {
            jToggleButtonConfort.setText("Automatico");
            try {
                teensy.sendData("xxxxxxxxxx");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            jToggleButtonConfort.setText("Manual");
            try {
                teensy.sendData("wwwwwwwwww");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_jToggleButtonConfortActionPerformed

    private void jToggleButtonIntrusosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonIntrusosActionPerformed
        if (jToggleButtonIntrusos.getText().equals("Manual")) {
            jToggleButtonIntrusos.setText("Automatico");
            try {
                teensy.sendData("ssssssssss");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            jToggleButtonIntrusos.setText("Manual");
            try {
                teensy.sendData("tttttttttt");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_jToggleButtonIntrusosActionPerformed

    private void jToggleButtonEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEnergiaActionPerformed
        if (jToggleButtonEnergia.getText().equals("Manual")) {
            jToggleButtonEnergia.setText("Automatico");
            try {
                teensy.sendData("vvvvvvvvv");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            jToggleButtonEnergia.setText("Manual");
            try {
                teensy.sendData("uuuuuuuu");
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
//            try {
//                Thread.sleep(500);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_jToggleButtonEnergiaActionPerformed

    private void jSliderTemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderTemperaturaStateChanged
        int valu = jSliderTemperatura.getValue();
        jLabelTempL.setText(valu + " ºC");
        char convertirDato = (char) valu;
        String enviarDato = "";
        for (int i = 0; i <= 1; i++) {
            enviarDato += convertirDato;
        }
        inhibidorTemp++;
        if (inhibidorTemp > 3) {
            //System.out.println(enviarDato);
            try {
                teensy.sendData(enviarDato);
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jSliderTemperaturaStateChanged

    private void jSliderHumedadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHumedadStateChanged
        int valu = jSliderHumedad.getValue();
        jLabelHumeL.setText(valu + " %");
        char convertirDato = (char) valu;
        String enviarDato = "";
        for (int i = 0; i <= 1; i++) {
            enviarDato += convertirDato;
        }
        inhibidorHume++;
        if (inhibidorHume > 3) {
            //System.out.println(enviarDato);
            try {
                teensy.sendData(enviarDato);
            } catch (ArduinoException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(Control.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jSliderHumedadStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHumeL;
    private javax.swing.JLabel jLabelHumedad;
    private javax.swing.JLabel jLabelTempL;
    private javax.swing.JLabel jLabelTemperatura;
    private javax.swing.JPanel jPAccidentes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelConfort;
    private javax.swing.JPanel jPanelMAhorroEnergia;
    private javax.swing.JSlider jSliderHumedad;
    private javax.swing.JSlider jSliderTemperatura;
    private javax.swing.JTabbedPane jTPMAhorroEnergia;
    private javax.swing.JToggleButton jToggleButtonAccidentes;
    private javax.swing.JToggleButton jToggleButtonConfort;
    private javax.swing.JToggleButton jToggleButtonEnergia;
    private javax.swing.JToggleButton jToggleButtonIntrusos;
    // End of variables declaration//GEN-END:variables
}
