/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.panamahitek.PanamaHitek_Arduino;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import stream.StreamData;

/**
 *
 * @author xyges
 */
public class Monitor extends javax.swing.JInternalFrame implements Runnable {

    PanamaHitek_Arduino teensy;
    Thread hilo;
    Boolean ejecucion;
    StreamData datos;

    public Monitor(PanamaHitek_Arduino teensy, StreamData datos) {
        this.teensy = teensy;
        this.datos = datos;
                initComponents();
        ejecucion = false;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //System.exit(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIndicadorLuces = new javax.swing.JLabel();
        jLIndicadorIncendio = new javax.swing.JLabel();
        jLIndicadorIntrusos = new javax.swing.JLabel();
        jLEstadoDeIntrusos = new javax.swing.JLabel();
        jLIndicadorHumo = new javax.swing.JLabel();
        jLEstadoDeIncendio = new javax.swing.JLabel();
        jLEstadoDeLuces1 = new javax.swing.JLabel();
        jLEstadoHumo = new javax.swing.JLabel();
        jToggleButtonSwitch = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Monitor de eventos");

        jLIndicadorLuces.setFont(new java.awt.Font("Serif", 1, 72)); // NOI18N
        jLIndicadorLuces.setText("■");
        jLIndicadorLuces.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLIndicadorIncendio.setFont(new java.awt.Font("Serif", 1, 72)); // NOI18N
        jLIndicadorIncendio.setText("■");
        jLIndicadorIncendio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLIndicadorIntrusos.setFont(new java.awt.Font("Serif", 1, 72)); // NOI18N
        jLIndicadorIntrusos.setText("■");
        jLIndicadorIntrusos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLEstadoDeIntrusos.setText("Intruso");

        jLIndicadorHumo.setFont(new java.awt.Font("Serif", 1, 72)); // NOI18N
        jLIndicadorHumo.setText("■");
        jLIndicadorHumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLEstadoDeIncendio.setText("Incendio");

        jLEstadoDeLuces1.setText("Luces");

        jLEstadoHumo.setText("Humo/Gas");

        jToggleButtonSwitch.setText("ON");
        jToggleButtonSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButtonSwitch)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLIndicadorLuces)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLEstadoDeLuces1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLIndicadorHumo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLEstadoHumo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLIndicadorIntrusos)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLEstadoDeIntrusos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLIndicadorIncendio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLEstadoDeIncendio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToggleButtonSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLIndicadorLuces, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLIndicadorIncendio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLIndicadorIntrusos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLIndicadorHumo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEstadoHumo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEstadoDeIntrusos)
                        .addComponent(jLEstadoDeIncendio)
                        .addComponent(jLEstadoDeLuces1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSwitchActionPerformed
        if (ejecucion == false) {
            ejecucion = true;
            hilo = new Thread(this);
            this.hilo.start();
            jToggleButtonSwitch.setText("OFF");
        } else {
            jToggleButtonSwitch.setText("ON");
            ejecucion = false;;
            jLIndicadorIncendio.setForeground(Color.BLACK);
            jLIndicadorIntrusos.setForeground(Color.BLACK);
            jLIndicadorLuces.setForeground(Color.BLACK);
            jLIndicadorHumo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jToggleButtonSwitchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEstadoDeIncendio;
    private javax.swing.JLabel jLEstadoDeIntrusos;
    private javax.swing.JLabel jLEstadoDeLuces1;
    private javax.swing.JLabel jLEstadoHumo;
    private javax.swing.JLabel jLIndicadorHumo;
    private javax.swing.JLabel jLIndicadorIncendio;
    private javax.swing.JLabel jLIndicadorIntrusos;
    private javax.swing.JLabel jLIndicadorLuces;
    private javax.swing.JToggleButton jToggleButtonSwitch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (ejecucion) {
            try {
                if (datos.humo == 0) {
                    jLIndicadorHumo.setForeground(Color.RED);
                } else {
                    jLIndicadorHumo.setForeground(Color.BLACK);
                }
                if (datos.luces == 1) {
                    jLIndicadorLuces.setForeground(Color.GREEN);
                } else {
                    jLIndicadorLuces.setForeground(Color.BLACK);
                }
                if (datos.intruso == 1) {
                    jLIndicadorIntrusos.setForeground(Color.red);
                } else {
                    jLIndicadorIntrusos.setForeground(Color.BLACK);
                }
                if (datos.fuego == 0) {
                    jLIndicadorIncendio.setForeground(Color.red);
                } else {
                    jLIndicadorIncendio.setForeground(Color.BLACK);
                }
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Monitor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
